// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2-v0kqyj3TJO1wUdVzGNZzTx5M76q5Zk',
    appId: '1:88729314159:web:0c4eb3d724cafc55bbbe9a',
    messagingSenderId: '88729314159',
    projectId: 'comms-426a1',
    authDomain: 'comms-426a1.firebaseapp.com',
    storageBucket: 'comms-426a1.firebasestorage.app',
    measurementId: 'G-QG6YCHY2S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG8VXwZvkKVsGsKvAru_uy2m9_VheUZpc',
    appId: '1:88729314159:android:7b6789d6d993ad4bbbbe9a',
    messagingSenderId: '88729314159',
    projectId: 'comms-426a1',
    storageBucket: 'comms-426a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgknfXVdJDTQgziGvEX8ZxaXZodXxwPWQ',
    appId: '1:88729314159:ios:238a78fab28b8ad5bbbe9a',
    messagingSenderId: '88729314159',
    projectId: 'comms-426a1',
    storageBucket: 'comms-426a1.firebasestorage.app',
    iosBundleId: 'com.example.commsFlutter',
  );
}
